### ISSUE TITLE
-Y flag is applied inconsistently between bash and C tests

### ISSUE THREAD

**Issue by carlilek** [VI4IO/io500-app#19]
The C app correctly only applies the -Y flag to the mdtest write phases, while the io500_fixed.sh script applies it to all phases of mdtest, which skews the results (at least for certain filesystems) away from the SC19 results. 

I believe this is the section of io500_fixed.sh that is incorrect: 

`183   params_md_easy="-F -P -Y -d $io500_workdir/mdt_easy -n $io500_mdtest_easy_files_per_proc $io500_mdt    est_easy_params -x $io500_workdir/mdt_easy-stonewall -N 1"
184   result_file=$io500_result_dir/$phase.txt
`

I believe that the -Y flag should be added in the if [[ "$1" == "write ]]; then section in order to maintain consistency with SC19 testing and the C app. 

The mdtest_hard section has the same issue.

**Comment by adilger** [comment]
This is fixed in io-500-dev commit 3de4e2d795 to remove the -Y flag from the read phases, which was unintentional.
