### ISSUE TITLE
io500.sh does not pass correct parameters to the bash script for find

### ISSUE THREAD

**Issue by carlilek** [VI4IO/io500-app#20]
The bash version of the benchmark appears to ignore the parameters under the [find] section of the config.ini file, namely
pfind-steal-next
pfind-queue-length
pfind-parallelize-single-dir-access-using-hashing
nproc

The last of them would probably require a fair amount of extra code to reinterpret the nproc requested to new mpirun_args.

Evidence

from config.ini file:
```[find]

#Pfind Steal from next

pfind-steal-next = TRUE

#Pfind queue length

pfind-queue-length = 20000

#Pfind with hashing

pfind-parallelize-single-dir-access-using-hashing = TRUE

#Set the number of processes for pfind

#nproc = 900
```

from bash script output:
`[Starting] find [Exec] mpiexec -np 300 -ppn 30 -f /io500/io500-isc20/io500-app/hostfile-10-h09 --bootstrap ssh /io500/io500-isc20/io500-app/bin/pfind ./datadir/2020.06.01-13.50.21-scr -newer ./datadir/2020.06.01-13.50.21-scr/timestampfile -size 3901c -name "*01*"
`

from C script:
`[find] t_start = 2020-06-01 14:11:03 exe = ./pfind ./datadir/2020.06.01-13.50.21-app -newer ./datadir/2020.06.01-13.50.21-app/timestampfile -size 3901c -name *01* -C -N -H 1 -q 20000
`

See https://github.com/VI4IO/io-500-dev/issues/70 for discussion. I moved it to here because it is an issue with the io500.sh wrapper script under io500-app, rather than a core issue with io-500-dev. 

The workaround in that thread of putting the flags and parameters in external-extra-args only applies to the bash script and the C app requires that the named parameters are set. It ignores external-extra-args when running pfind.

**Comment by adilger** [comment]
This was fixed by commit 0da7c14f6e.

**Comment by adilger** [comment]
My bad, the commit 0da7c14f6e fixed the `external-extra-args` parsing, but it doesn't actually parse the pfind arguments directly.

**Comment by adilger** [comment]
The bash script is deprecated. For SC'20 only the C-app is needed.
