### ISSUE TITLE
Lustre FS parameters

### ISSUE THREAD

**Issue by abrekhov** [VI4IO/io500-app#22]
Hi! 
There is clause in rules about pre-creating:

> The file names for the mdtest output files may not be pre-created.

Does it mean that it's forbidden to tune folders with lustre tools?
If it's allowed to do so where to put commands (which part of io500.sh)? 
Thanks!

**Comment by JulianKunkel** [comment]
It means you cannot pre-create the sub-directories with specific flags, you can create, e.g., the md-easy and md-hard top-level directories for the benchmarks using different flags:
For the submission of the ISC20 list, you can put it into the io500.sh script: have a look at the submission here:
https://www.vi4io.org/assets/io500/2020-06/isc-20-dkrz-10nodes.tgz
Which shows how it worked for Lustre. In the long run, one will have to put this into the submission script that calls the app.

**Comment by abrekhov** [comment]
Julian thank you very much! It really helps!
